# QC Entity Inventory Explorer

This notebook allows exploration of QC entity inventory results generated
by `qc_entity_inventory.py`.  

We can inspect:
- The top entities per class
- Rare entities with low occurrences

The insights gained here will help define **rules for annotation**,
to be documented in [`docs/annotation_rules.md`](../docs/annotation_rules.md).  
For example, these rules may include:
- Standardizing numeric formats, such as temperatures in Kelvin (`300 K` → `300K`)
- Removing unnecessary spaces between values and units
- Normalizing synonyms or alternative spellings of entity names
...

## Load libraries and setup

In [37]:
from pathlib import Path

import pandas as pd

In [38]:
%load_ext watermark
%watermark

The watermark extension is already loaded. To reload it, use:
  %reload_ext watermark
Last updated: 2026-02-28T03:41:01.111302+01:00

Python implementation: CPython
Python version       : 3.13.0
IPython version      : 8.13.2

Compiler    : Clang 18.1.8
OS          : Linux
Release     : 6.8.0-51-generic
Machine     : x86_64
Processor   : x86_64
CPU cores   : 4
Architecture: 64bit

In [39]:
# Folder containing the QC entity inventory files
out_folder = Path("../results/qc_annotations")

# Dictionary to store data per class
entity_data = {}

## Load data

In [40]:
for file_path in out_folder.glob("*.txt"):
    with file_path.open(encoding="utf-8") as f:
        lines = f.readlines()

    # Skip header lines (start with #)
    data_lines = [line.strip() for line in lines if not line.startswith("#")]

    # Build DataFrame
    df = pd.DataFrame(
        [line.split("\t") for line in data_lines],
        columns=["entity", "count", "annotation_paths"]
    )
    df.loc[:, "count"] = df["count"].astype(int)

    # Compute totals
    total_occurrences = df["count"].sum()
    unique_entities = df.shape[0]

    # Store per class
    entity_data[file_path.stem] = df

print("Annotation summary by class:")
print("-" * 50)
print(f"{'Class':20} | {'Total occurrences':17} | {'Unique entities':15}")
print("-" * 50)

# Trier par total_occurrences décroissant
for class_name, df in sorted(entity_data.items(), key=lambda x: x[1]["count"].sum(), 
    reverse=True):
    total_occurrences = df["count"].sum()
    unique_entities = df.shape[0]
    print(f"{class_name:20} | {total_occurrences:17} | {unique_entities:15}")

print("-" * 50)

Annotation summary by class:
--------------------------------------------------
Class                | Total occurrences | Unique entities
--------------------------------------------------
MOL                  |              3240 |            1071
FFM                  |               414 |             106
FFMNAME              |               382 |              94
SOFTNAME             |               331 |              78
STIME                |               164 |              85
TEMP                 |               125 |              50
SOFTVERS             |                81 |              49
FFMVERS              |                19 |               6
--------------------------------------------------

##

## Molecules 🧬

In [41]:
df = entity_data["MOL"].sort_values("count", ascending=False)
df

,entity,count,annotation_paths
0,water,189,"[annotations/v3/zenodo_3613573.json, annotatio..."
1,popc,99,"[annotations/v3/zenodo_3613573.json, annotatio..."
2,cholesterol,53,"[annotations/v3/zenodo_259443.json, annotation..."
3,dppc,53,"[annotations/v3/zenodo_259443.json, annotation..."
4,nacl,44,"[annotations/v3/zenodo_51760.json, annotations..."
...,...,...,...
709,dianions,1,[annotations/v3/figshare_2527738.json]
708,diacylglycerol,1,[annotations/v3/figshare_12986024.json]
707,di-ubiquitin,1,[annotations/v3/zenodo_3878218.json]
706,"di-, tri- and tetra-ubiquitin",1,[annotations/v3/zenodo_3878218.json]
1070,β-lactamases,1,[annotations/v3/figshare_12312368.json]

In [42]:
total_entities = len(df)
rare_df = df[df["count"] == 1]
num_rare = len(rare_df)

print(f"Rare molecules (count = 1): {num_rare} / {total_entities} total entities")
rare_df

Rare molecules (count = 1): 531 / 1071 total entities

,entity,count,annotation_paths
900,nucleotide,1,[annotations/v3/zenodo_7440399.json]
889,nitric acid,1,[annotations/v3/figshare_22151355.json]
890,nitrogen,1,[annotations/v3/figshare_6965759.json]
891,nmda receptor,1,[annotations/v3/zenodo_7301759.json]
892,nmdars,1,[annotations/v3/zenodo_7301759.json]
...,...,...,...
709,dianions,1,[annotations/v3/figshare_2527738.json]
708,diacylglycerol,1,[annotations/v3/figshare_12986024.json]
707,di-ubiquitin,1,[annotations/v3/zenodo_3878218.json]
706,"di-, tri- and tetra-ubiquitin",1,[annotations/v3/zenodo_3878218.json]
1070,β-lactamases,1,[annotations/v3/figshare_12312368.json]

## Force Field Model Name 🛠️

In [43]:
df = entity_data["FFMNAME"].sort_values("count", ascending=False)
df

       entity count                                   annotation_paths
0      charmm    40  [annotations/v3/zenodo_1198454.json, annotatio...
1     martini    34  [annotations/v3/figshare_13836577.json, annota...
2    charmm36    33  [annotations/v3/figshare_14225919.json, annota...
3       amber    26  [annotations/v3/zenodo_7273800.json, annotatio...
4       tip3p    23  [annotations/v3/zenodo_259443.json, annotation...
..        ...   ...                                                ...
65       ff03     1             [annotations/v3/figshare_2532337.json]
66      ff03*     1             [annotations/v3/figshare_2532337.json]
67      ff03w     1             [annotations/v3/figshare_2532337.json]
69       ff99     1             [annotations/v3/figshare_2532337.json]
93  trappe-ua     1            [annotations/v3/figshare_13836577.json]

[94 rows x 3 columns]

In [44]:
total_entities = len(df)
rare_df = df[df["count"] == 1]
num_rare = len(rare_df)

print(f"Rare force field or model names (count = 1): {num_rare} / {total_entities} total entities")
rare_df

Rare force field or model names (count = 1): 43 / 94 total entities

,entity,count,annotation_paths
77,l-opls,1,[annotations/v3/figshare_14225919.json]
80,martini 2.2p,1,[annotations/v3/zenodo_6973476.json]
79,lipid17,1,[annotations/v3/zenodo_3610470.json]
78,lipid14,1,[annotations/v3/zenodo_34415.json]
74,generalized amber force field,1,[annotations/v3/figshare_5106286.json]
76,gromos54a7,1,[annotations/v3/figshare_4806544.json]
75,gromos 53a6,1,[annotations/v3/figshare_11771604.json]
82,martini 3.0,1,[annotations/v3/zenodo_6010416.json]
81,martini 3,1,[annotations/v3/zenodo_5060102.json]
86,parmbsc0,1,[annotations/v3/figshare_19102457.json]
83,martini cg,1,[annotations/v3/figshare_2154835.json]
84,opls-aa/m,1,[annotations/v3/figshare_9941741.json]
85,parm99,1,[annotations/v3/figshare_19102457.json]
72,gap,1,[annotations/v3/zenodo_7112198.json]
87,q4md-cd,1,[annotations/v3/figshare_11808522.json]
88,rsff1,1,[annotations/v3/figshare_3207154.json]
89,schnet,1,[annotations/v3/zenodo_7112198.json]
90,tip,1,[annotations/v3/figshare_12064266.json]
91,tip4p-ew,1,[annotations/v3/figshare_12987701.json]
92,tip4p/2005,1,[annotations/v3/figshare_13836577.json]
73,gdml,1,[annotations/v3/zenodo_7112198.json]
68,ff96,1,[annotations/v3/figshare_2532337.json]
71,ff99sb-ildn,1,[annotations/v3/figshare_2532337.json]
59,bind3p,1,[annotations/v3/figshare_11808522.json]
51,'berger,1,[annotations/v3/zenodo_51748.json]
52,amber ff14sb,1,[annotations/v3/figshare_6575438.json]
53,amber ff99sb,1,[annotations/v3/zenodo_6349893.json]
54,amber ff99sb-ildn,1,[annotations/v3/zenodo_6349893.json]
55,amber14,1,[annotations/v3/zenodo_4805388.json]
56,amber14sb,1,[annotations/v3/zenodo_3975394.json]
57,amoeba,1,[annotations/v3/figshare_8258741.json]
58,autodock,1,[annotations/v3/figshare_121241.json]
60,c36m.,1,[annotations/v3/figshare_9788852.json]
70,ff99sb*,1,[annotations/v3/figshare_2532337.json]
61,charmm 27,1,[annotations/v3/figshare_3983526.json]
62,charmm36 forcefield (version july 2020),1,[annotations/v3/zenodo_7037843.json]
63,charmm36m.,1,[annotations/v3/zenodo_6592231.json]
64,charmm36mw,1,[annotations/v3/zenodo_5573728.json]
65,ff03,1,[annotations/v3/figshare_2532337.json]
66,ff03*,1,[annotations/v3/figshare_2532337.json]
67,ff03w,1,[annotations/v3/figshare_2532337.json]
69,ff99,1,[annotations/v3/figshare_2532337.json]
93,trappe-ua,1,[annotations/v3/figshare_13836577.json]

## Force Field Model version 🔢

In [45]:
df = entity_data["FFMVERS"].sort_values("count", ascending=False)
df

         entity count                                   annotation_paths
0            36    13  [annotations/v3/zenodo_7572990.json, annotatio...
1        53a6_l     2  [annotations/v3/zenodo_14594.json, annotations...
2           36m     1               [annotations/v3/zenodo_7533587.json]
3          54a7     1             [annotations/v3/figshare_8046437.json]
4        ff14sb     1               [annotations/v3/zenodo_7533587.json]
5  v. june 2015     1               [annotations/v3/zenodo_4300706.json]

In [46]:
total_entities = len(df)
rare_df = df[df["count"] == 1]
num_rare = len(rare_df)

print(
    f"Rare force field or model versions (count = 1): {num_rare} / {total_entities} total entities"
)
rare_df

Rare force field or model versions (count = 1): 4 / 6 total entities

         entity count                        annotation_paths
2           36m     1    [annotations/v3/zenodo_7533587.json]
3          54a7     1  [annotations/v3/figshare_8046437.json]
4        ff14sb     1    [annotations/v3/zenodo_7533587.json]
5  v. june 2015     1    [annotations/v3/zenodo_4300706.json]

## Software name ⚙️

In [47]:
df = entity_data["SOFTNAME"].sort_values("count", ascending=False)
df

        entity count                                   annotation_paths
0      gromacs   134  [annotations/v3/zenodo_51760.json, annotations...
1       lammps    18  [annotations/v3/zenodo_7234728.json, annotatio...
2        amber    16  [annotations/v3/zenodo_6870476.json, annotatio...
3          vmd    15  [annotations/v3/figshare_1381865.json, annotat...
4   charmm-gui     8  [annotations/v3/zenodo_30904.json, annotations...
..         ...   ...                                                ...
50      github     1               [annotations/v3/zenodo_3610470.json]
51       glide     1               [annotations/v3/zenodo_3567651.json]
52      glycam     1               [annotations/v3/zenodo_5592299.json]
53  glycam-web     1            [annotations/v3/figshare_12272015.json]
77      visual     1               [annotations/v3/zenodo_6879091.json]

[78 rows x 3 columns]

In [48]:
total_entities = len(df)
rare_df = df[df["count"] == 1]
num_rare = len(rare_df)

print(f"Rare software names (count = 1): {num_rare} / {total_entities} total entities")
rare_df

Rare software names (count = 1): 43 / 78 total entities

            entity count                         annotation_paths
56      hoomd-blue     1     [annotations/v3/zenodo_6957888.json]
64           optim     1     [annotations/v3/zenodo_7107608.json]
63           namd2     1     [annotations/v3/zenodo_4245236.json]
62          molsim     1     [annotations/v3/zenodo_7523635.json]
59         maestro     1     [annotations/v3/zenodo_3362889.json]
61          molpro     1     [annotations/v3/zenodo_6791151.json]
60             moe     1     [annotations/v3/zenodo_4245236.json]
66      pathsample     1     [annotations/v3/zenodo_7107608.json]
58       lipidbook     1       [annotations/v3/zenodo_13392.json]
65       paramchem     1     [annotations/v3/zenodo_6988344.json]
70      pyinteraph     1     [annotations/v3/zenodo_1346073.json]
67           pmemd     1   [annotations/v3/figshare_4757161.json]
68          prmtop     1     [annotations/v3/zenodo_6870476.json]
69           prody     1   [annotations/v3/figshare_4806544.json]
71           pymol     1     [annotations/v3/zenodo_6349893.json]
72           rdock     1     [annotations/v3/zenodo_2586559.json]
73         rosetta     1  [annotations/v3/figshare_19082291.json]
74       swissprot     1     [annotations/v3/zenodo_4730896.json]
75        torchani     1     [annotations/v3/zenodo_5060102.json]
76        unitymol     1     [annotations/v3/zenodo_5060102.json]
57        intermol     1     [annotations/v3/zenodo_5592299.json]
39          asegui     1     [annotations/v3/zenodo_5060102.json]
55  gromacs-2020.6     1     [annotations/v3/zenodo_6349893.json]
44      deepmd-kit     1     [annotations/v3/zenodo_7234728.json]
35           acemd     1   [annotations/v3/figshare_3983526.json]
36            aimd     1     [annotations/v3/zenodo_7234728.json]
37       alphafold     1     [annotations/v3/zenodo_5642866.json]
38             ase     1     [annotations/v3/zenodo_5060102.json]
40        autodock     1     [annotations/v3/zenodo_2586559.json]
41       autodock4     1     [annotations/v3/zenodo_6592231.json]
42        chimerax     1     [annotations/v3/zenodo_7007107.json]
43          colvar     1     [annotations/v3/zenodo_7323535.json]
45       doglycans     1   [annotations/v3/figshare_5496910.json]
54        gromacs,     1   [annotations/v3/figshare_5532214.json]
46         flexaid     1     [annotations/v3/zenodo_2586559.json]
47        gaussian     1     [annotations/v3/zenodo_7273800.json]
48      gaussian16     1     [annotations/v3/zenodo_3361945.json]
49           gibbs     1   [annotations/v3/figshare_2267512.json]
50          github     1     [annotations/v3/zenodo_3610470.json]
51           glide     1     [annotations/v3/zenodo_3567651.json]
52          glycam     1     [annotations/v3/zenodo_5592299.json]
53      glycam-web     1  [annotations/v3/figshare_12272015.json]
77          visual     1     [annotations/v3/zenodo_6879091.json]

## Software version 🔢

In [49]:
df = entity_data["SOFTVERS"].sort_values("count", ascending=False)
df

,entity,count,annotation_paths
0,3.x,7,"[annotations/v3/zenodo_51760.json, annotations..."
1,4.0.7,7,"[annotations/v3/zenodo_14591.json, annotations..."
2,4.5,6,"[annotations/v3/zenodo_15550.json, annotations..."
3,5.1.4,4,"[annotations/v3/zenodo_1198454.json, annotatio..."
4,2020,3,"[annotations/v3/zenodo_4245236.json, annotatio..."
5,5.0.3,3,"[annotations/v3/zenodo_30904.json, annotations..."
11,5.1.1,2,"[annotations/v3/zenodo_55565.json, annotations..."
13,v5,2,"[annotations/v3/zenodo_247386.json, annotation..."
12,7,2,"[annotations/v3/figshare_5247880.json, annotat..."
10,4.5.,2,"[annotations/v3/zenodo_44622.json, annotations..."
9,2018.3,2,"[annotations/v3/zenodo_3865919.json, annotatio..."
8,19,2,"[annotations/v3/zenodo_3786821.json, annotatio..."
7,16,2,"[annotations/v3/figshare_4757161.json, annotat..."
6,(v. 2016.4),2,"[annotations/v3/zenodo_3950029.json, annotatio..."
39,simulation engine version 2019.4,1,[annotations/v3/zenodo_3667662.json]
33,5.0.3.,1,[annotations/v3/zenodo_34415.json]
34,5.0.6,1,[annotations/v3/zenodo_1293813.json]
35,5.0.x,1,[annotations/v3/zenodo_838635.json]
36,5.1.5,1,[annotations/v3/zenodo_6973476.json]
37,5.1.x,1,[annotations/v3/zenodo_6817824.json]
38,molecular dynamics,1,[annotations/v3/zenodo_6879091.json]
46,version 2.6.0,1,[annotations/v3/zenodo_3865919.json]
40,software (v. 2016.4),1,[annotations/v3/zenodo_3901180.json]
41,stable dec. 2018,1,[annotations/v3/zenodo_7273800.json]
42,tools,1,[annotations/v3/figshare_5496910.json]
43,v.4.6.5,1,[annotations/v3/figshare_13135976.json]
44,v2.4,1,[annotations/v3/zenodo_7533587.json]
45,v9.16,1,[annotations/v3/figshare_13135976.json]
31,4.6->,1,[annotations/v3/zenodo_259443.json]
47,version 4.6,1,[annotations/v3/figshare_5532214.json]
32,4.6.5,1,[annotations/v3/zenodo_3908769.json]
24,2018.0,1,[annotations/v3/zenodo_1488094.json]
30,4.5.6,1,[annotations/v3/zenodo_3236015.json]
20,2016.1,1,[annotations/v3/zenodo_3248612.json]
14,"(dec 2018, stable)",1,[annotations/v3/zenodo_7273800.json]
15,(v. 2020),1,[annotations/v3/zenodo_4300706.json]
16,(v4.6),1,[annotations/v3/zenodo_238943.json]
17,1.9.3,1,[annotations/v3/zenodo_4730896.json]
18,16 rev b01,1,[annotations/v3/zenodo_7273800.json]
19,2.0,1,[annotations/v3/zenodo_3696970.json]
21,2016.2-dev-20170105-4feb0be,1,[annotations/v3/zenodo_1219494.json]
29,3.3.3,1,[annotations/v3/figshare_4806544.json]
22,2016.3,1,[annotations/v3/zenodo_1167532.json]
23,2018,1,[annotations/v3/zenodo_6755131.json]
25,2019,1,[annotations/v3/zenodo_3592499.json]
26,2020.4,1,[annotations/v3/zenodo_7007107.json]
27,2021,1,[annotations/v3/zenodo_7533587.json]
28,2021.4,1,[annotations/v3/zenodo_7323535.json]
48,vina,1,[annotations/v3/zenodo_2586559.json]

In [50]:
total_entities = len(df)
rare_df = df[df["count"] == 1]
num_rare = len(rare_df)

print(f"Rare software versions (count = 1): {num_rare} / {total_entities} total entities")
rare_df

Rare software versions (count = 1): 35 / 49 total entities

,entity,count,annotation_paths
39,simulation engine version 2019.4,1,[annotations/v3/zenodo_3667662.json]
33,5.0.3.,1,[annotations/v3/zenodo_34415.json]
34,5.0.6,1,[annotations/v3/zenodo_1293813.json]
35,5.0.x,1,[annotations/v3/zenodo_838635.json]
36,5.1.5,1,[annotations/v3/zenodo_6973476.json]
37,5.1.x,1,[annotations/v3/zenodo_6817824.json]
38,molecular dynamics,1,[annotations/v3/zenodo_6879091.json]
46,version 2.6.0,1,[annotations/v3/zenodo_3865919.json]
40,software (v. 2016.4),1,[annotations/v3/zenodo_3901180.json]
41,stable dec. 2018,1,[annotations/v3/zenodo_7273800.json]
42,tools,1,[annotations/v3/figshare_5496910.json]
43,v.4.6.5,1,[annotations/v3/figshare_13135976.json]
44,v2.4,1,[annotations/v3/zenodo_7533587.json]
45,v9.16,1,[annotations/v3/figshare_13135976.json]
31,4.6->,1,[annotations/v3/zenodo_259443.json]
47,version 4.6,1,[annotations/v3/figshare_5532214.json]
32,4.6.5,1,[annotations/v3/zenodo_3908769.json]
24,2018.0,1,[annotations/v3/zenodo_1488094.json]
30,4.5.6,1,[annotations/v3/zenodo_3236015.json]
20,2016.1,1,[annotations/v3/zenodo_3248612.json]
14,"(dec 2018, stable)",1,[annotations/v3/zenodo_7273800.json]
15,(v. 2020),1,[annotations/v3/zenodo_4300706.json]
16,(v4.6),1,[annotations/v3/zenodo_238943.json]
17,1.9.3,1,[annotations/v3/zenodo_4730896.json]
18,16 rev b01,1,[annotations/v3/zenodo_7273800.json]
19,2.0,1,[annotations/v3/zenodo_3696970.json]
21,2016.2-dev-20170105-4feb0be,1,[annotations/v3/zenodo_1219494.json]
29,3.3.3,1,[annotations/v3/figshare_4806544.json]
22,2016.3,1,[annotations/v3/zenodo_1167532.json]
23,2018,1,[annotations/v3/zenodo_6755131.json]
25,2019,1,[annotations/v3/zenodo_3592499.json]
26,2020.4,1,[annotations/v3/zenodo_7007107.json]
27,2021,1,[annotations/v3/zenodo_7533587.json]
28,2021.4,1,[annotations/v3/zenodo_7323535.json]
48,vina,1,[annotations/v3/zenodo_2586559.json]

## Simulation time ⏱

In [51]:
df = entity_data["STIME"].sort_values("count", ascending=False)
df

         entity count                                   annotation_paths
0         500ns    12  [annotations/v3/zenodo_1009027.json, annotatio...
2        200 ns     9  [annotations/v3/zenodo_259443.json, annotation...
3   microsecond     9  [annotations/v3/figshare_7924394.json, annotat...
1         100ns     9  [annotations/v3/zenodo_14591.json, annotations...
4        500 ns     8  [annotations/v3/zenodo_3613573.json, annotatio...
..          ...   ...                                                ...
49           20     1               [annotations/v3/zenodo_6973476.json]
50    200-300ns     1               [annotations/v3/zenodo_7572990.json]
51         27ns     1               [annotations/v3/zenodo_3908769.json]
52         298k     1                 [annotations/v3/zenodo_13814.json]
84   nanosecond     1             [annotations/v3/figshare_2271034.json]

[85 rows x 3 columns]

In [52]:
total_entities = len(df)
rare_df = df[df["count"] == 1]
num_rare = len(rare_df)

print(f"Rare simulation times (count = 1): {num_rare} / {total_entities} total entities")
rare_df

Rare simulation times (count = 1): 60 / 85 total entities

               entity count                         annotation_paths
69            4200 ns     1     [annotations/v3/zenodo_3228177.json]
63             360 ns     1     [annotations/v3/zenodo_1198171.json]
67              40 ns     1     [annotations/v3/zenodo_7672195.json]
66             4.1 us     1     [annotations/v3/zenodo_7037843.json]
65             380 ns     1     [annotations/v3/zenodo_1198158.json]
64             370 ns     1     [annotations/v3/zenodo_1198454.json]
60            320.1 k     1     [annotations/v3/zenodo_5573728.json]
62              36 μs     1   [annotations/v3/figshare_7857659.json]
61            321.8 k     1     [annotations/v3/zenodo_5573728.json]
59            318.4 k     1     [annotations/v3/zenodo_5573728.json]
58            316.7 k     1     [annotations/v3/zenodo_5573728.json]
57            3000 ns     1     [annotations/v3/zenodo_3248612.json]
68               40ns     1       [annotations/v3/zenodo_13853.json]
81             800 ns     1      [annotations/v3/zenodo_259443.json]
70             450 ns     1   [annotations/v3/figshare_6575438.json]
71      5-microsecond     1   [annotations/v3/figshare_5532214.json]
72             500 ps     1  [annotations/v3/figshare_11808396.json]
73            5000 ns     1     [annotations/v3/zenodo_6817824.json]
74              500ps     1  [annotations/v3/figshare_11808396.json]
75               50ns     1       [annotations/v3/zenodo_15550.json]
76             600 ns     1  [annotations/v3/figshare_20359967.json]
77               60ns     1       [annotations/v3/zenodo_13814.json]
78      6microseconds     1     [annotations/v3/zenodo_3975394.json]
79                6µs     1   [annotations/v3/figshare_3983526.json]
80     8 microseconds     1     [annotations/v3/zenodo_5226209.json]
55              300 k     1  [annotations/v3/figshare_20009556.json]
82     87 microsecond     1     [annotations/v3/zenodo_7323535.json]
83  multi-microsecond     1     [annotations/v3/zenodo_7301759.json]
56    300 nanoseconds     1     [annotations/v3/zenodo_5153261.json]
42            1080 ns     1     [annotations/v3/zenodo_3778112.json]
54              30 ns     1  [annotations/v3/figshare_18095690.json]
53               3 μs     1     [annotations/v3/zenodo_7007107.json]
25             0.5 μs     1     [annotations/v3/zenodo_4106413.json]
26                0.6     1   [annotations/v3/figshare_5642866.json]
27           0.633 us     1     [annotations/v3/zenodo_7037843.json]
28            0.79 ns     1  [annotations/v3/figshare_18095690.json]
29               1 ns     1   [annotations/v3/figshare_8046437.json]
30               1 µs     1     [annotations/v3/zenodo_6592231.json]
31             1.0 us     1     [annotations/v3/zenodo_7037843.json]
32      1.5 micro-sec     1     [annotations/v3/zenodo_6349893.json]
33             1.6 ns     1  [annotations/v3/figshare_20376757.json]
34             1.6 μs     1   [annotations/v3/figshare_5642866.json]
35              10 ns     1     [annotations/v3/zenodo_5060102.json]
36              10 µs     1     [annotations/v3/zenodo_6973476.json]
37              10 μs     1   [annotations/v3/figshare_7952567.json]
38    100 nanoseconds     1     [annotations/v3/zenodo_5079480.json]
39          100-200ns     1     [annotations/v3/zenodo_7572990.json]
40         100–200 ns     1      [annotations/v3/zenodo_838635.json]
41            1069 ns     1     [annotations/v3/zenodo_1219494.json]
43              11 ns     1       [annotations/v3/zenodo_51750.json]
44              12 μs     1     [annotations/v3/zenodo_7007107.json]
45              120ns     1       [annotations/v3/zenodo_44622.json]
46             125 ns     1     [annotations/v3/zenodo_7007107.json]
47              167ns     1       [annotations/v3/zenodo_44660.json]
48             190 ns     1       [annotations/v3/zenodo_53212.json]
49                 20     1     [annotations/v3/zenodo_6973476.json]
50          200-300ns     1     [annotations/v3/zenodo_7572990.json]
51               27ns     1     [annotations/v3/zenodo_3908769.json]
52               298k     1       [annotations/v3/zenodo_13814.json]
84         nanosecond     1   [annotations/v3/figshare_2271034.json]

## Temperature 🌡️

In [53]:
df = entity_data["TEMP"].sort_values("count", ascending=False)
df

      entity count                                   annotation_paths
0       310k    18  [annotations/v3/zenodo_1198454.json, annotatio...
1      310 k    13  [annotations/v3/zenodo_259443.json, annotation...
2      300 k    10  [annotations/v3/zenodo_6380887.json, annotatio...
3      298 k     7  [annotations/v3/zenodo_1167532.json, annotatio...
4      323 k     6  [annotations/v3/zenodo_51760.json, annotations...
5       325k     5  [annotations/v3/zenodo_1009027.json, annotatio...
6       288k     4  [annotations/v3/zenodo_3950029.json, annotatio...
7       303k     4  [annotations/v3/zenodo_1009607.json, annotatio...
8       323k     4  [annotations/v3/zenodo_14591.json, annotations...
9       358k     4  [annotations/v3/zenodo_3950029.json, annotatio...
10    298.15     3  [annotations/v3/zenodo_30904.json, annotations...
11     313 k     3  [annotations/v3/zenodo_1293762.json, annotatio...
15      320k     2  [annotations/v3/zenodo_1009027.json, annotatio...
17     363 k     2  [annotations/v3/zenodo_7007107.json, annotatio...
16      338k     2  [annotations/v3/zenodo_1009027.json, annotatio...
14  318.15 k     2  [annotations/v3/figshare_16698491.json, annota...
12    283.15     2  [annotations/v3/figshare_16698491.json, annota...
13  298.15 k     2  [annotations/v3/zenodo_7112198.json, annotatio...
36  313.15 k     1            [annotations/v3/figshare_21726720.json]
37       315     1               [annotations/v3/zenodo_1009027.json]
38      315k     1               [annotations/v3/zenodo_1009027.json]
39       320     1               [annotations/v3/zenodo_2653735.json]
40      322k     1               [annotations/v3/zenodo_1009027.json]
41     333 k     1               [annotations/v3/zenodo_2653735.json]
42     338 k     1               [annotations/v3/zenodo_1009027.json]
34       303     1                [annotations/v3/zenodo_247386.json]
43     340 k     1               [annotations/v3/zenodo_6380887.json]
44      3500     1               [annotations/v3/zenodo_7234728.json]
45      363k     1               [annotations/v3/zenodo_7007107.json]
46     365 k     1            [annotations/v3/figshare_16715821.json]
47    4000 k     1               [annotations/v3/zenodo_7234728.json]
48  473.15 k     1            [annotations/v3/figshare_13836577.json]
35       310     1               [annotations/v3/zenodo_2653735.json]
25  273.15 k     1            [annotations/v3/figshare_12987701.json]
33      300k     1            [annotations/v3/figshare_16574000.json]
32      3000     1               [annotations/v3/zenodo_7234728.json]
31      298k     1               [annotations/v3/zenodo_1167532.json]
30       298     1               [annotations/v3/zenodo_2653735.json]
29     295 k     1             [annotations/v3/figshare_4541035.json]
28    293.15     1            [annotations/v3/figshare_21726720.json]
27     293 k     1                [annotations/v3/zenodo_259443.json]
26       285     1               [annotations/v3/zenodo_2653735.json]
24      2500     1               [annotations/v3/zenodo_7234728.json]
23        25     1            [annotations/v3/figshare_12661589.json]
22       242     1            [annotations/v3/figshare_12987701.json]
21     225 k     1               [annotations/v3/zenodo_4106413.json]
20     210 k     1            [annotations/v3/figshare_12987701.json]
19       200     1               [annotations/v3/zenodo_4106413.json]
18     130 k     1            [annotations/v3/figshare_22213635.json]
49    5000 k     1            [annotations/v3/figshare_12218135.json]

In [55]:
total_entities = len(df)
rare_df = df[df["count"] == 1]
num_rare = len(rare_df)

print(f"Rare temperatures (count = 1): {num_rare} / {total_entities} total entities")
rare_df

Rare temperatures (count = 1): 32 / 50 total entities

      entity count                         annotation_paths
36  313.15 k     1  [annotations/v3/figshare_21726720.json]
37       315     1     [annotations/v3/zenodo_1009027.json]
38      315k     1     [annotations/v3/zenodo_1009027.json]
39       320     1     [annotations/v3/zenodo_2653735.json]
40      322k     1     [annotations/v3/zenodo_1009027.json]
41     333 k     1     [annotations/v3/zenodo_2653735.json]
42     338 k     1     [annotations/v3/zenodo_1009027.json]
34       303     1      [annotations/v3/zenodo_247386.json]
43     340 k     1     [annotations/v3/zenodo_6380887.json]
44      3500     1     [annotations/v3/zenodo_7234728.json]
45      363k     1     [annotations/v3/zenodo_7007107.json]
46     365 k     1  [annotations/v3/figshare_16715821.json]
47    4000 k     1     [annotations/v3/zenodo_7234728.json]
48  473.15 k     1  [annotations/v3/figshare_13836577.json]
35       310     1     [annotations/v3/zenodo_2653735.json]
25  273.15 k     1  [annotations/v3/figshare_12987701.json]
33      300k     1  [annotations/v3/figshare_16574000.json]
32      3000     1     [annotations/v3/zenodo_7234728.json]
31      298k     1     [annotations/v3/zenodo_1167532.json]
30       298     1     [annotations/v3/zenodo_2653735.json]
29     295 k     1   [annotations/v3/figshare_4541035.json]
28    293.15     1  [annotations/v3/figshare_21726720.json]
27     293 k     1      [annotations/v3/zenodo_259443.json]
26       285     1     [annotations/v3/zenodo_2653735.json]
24      2500     1     [annotations/v3/zenodo_7234728.json]
23        25     1  [annotations/v3/figshare_12661589.json]
22       242     1  [annotations/v3/figshare_12987701.json]
21     225 k     1     [annotations/v3/zenodo_4106413.json]
20     210 k     1  [annotations/v3/figshare_12987701.json]
19       200     1     [annotations/v3/zenodo_4106413.json]
18     130 k     1  [annotations/v3/figshare_22213635.json]
49    5000 k     1  [annotations/v3/figshare_12218135.json]