# **QC Entity Inventory Explorer 🔎**

This notebook allows exploration of QC entity inventory results generated
by `src/mdner_llm/utils/build_entity_vocab.py`.

We can inspect:

- The top entities per class
- Rare entities with low occurrences

The insights gained here will help define **rules for annotation**,
to be documented in [`docs/annotation_rules.md`](../docs/annotation_rules.md).

## Load libraries and setup

In [18]:
from pathlib import Path

from mdner_llm.utils.build_entity_vocab import process_qc_entity_inventory

In [19]:
%load_ext watermark
%watermark

The watermark extension is already loaded. To reload it, use:
  %reload_ext watermark
Last updated: 2026-03-26T01:32:27.528811+01:00

Python implementation: CPython
Python version       : 3.13.0
IPython version      : 8.13.2

Compiler    : Clang 18.1.8
OS          : Linux
Release     : 6.8.0-51-generic
Machine     : x86_64
Processor   : x86_64
CPU cores   : 4
Architecture: 64bit

## Load data

In [20]:
# Define the annotation directory
annotation_dir = Path("../../annotations/v3")
# Define the results directory
results_dir = Path("../../results/qc_annotations")

In [21]:
# Process the QC entity inventory
# Get dictionnary containing entity counts for each class label
entity_data = process_qc_entity_inventory(annotation_dir, results_dir)

2026-03-26 01:32:28 | INFO     | Starting QC entity inventory.
2026-03-26 01:32:28 | INFO     | Collecting entity counts.
2026-03-26 01:32:28 | SUCCESS  | Found 369 JSON annotation files.
2026-03-26 01:32:29 | SUCCESS  | Collected entity counts for 6 classes: FFM, MOL, SOFTNAME, SOFTVERS, STIME, TEMP!
2026-03-26 01:32:29 | INFO     | Saving QC inventory files to ../../results/qc_annotations.
2026-03-26 01:32:29 | SUCCESS  | QC entity inventory completed successfully!

In [22]:
print("Annotation summary by class:")
print("-" * 50)
print(f"{'Class':20} | {'Total occurrences':17} | {'Unique entities':15}")
print("-" * 50)

# Trier par total_occurrences décroissant
for class_name, df in sorted(
    entity_data.items(), key=lambda x: x[1]["count"].sum(), reverse=True
):
    total_occurrences = df["count"].sum()
    unique_entities = df.shape[0]
    print(f"{class_name:20} | {total_occurrences:17} | {unique_entities:15}")

print("-" * 50)

Annotation summary by class:
--------------------------------------------------
Class                | Total occurrences | Unique entities
--------------------------------------------------
MOL                  |              3022 |            1128
FFM                  |               403 |             106
SOFTNAME             |               361 |              78
STIME                |               168 |              86
TEMP                 |               142 |              60
SOFTVERS             |                99 |              56
--------------------------------------------------

##

## Molecules 🧬

In [23]:
df = entity_data["MOL"].sort_values("count", ascending=False)
df

,entity,count,annotation_paths
0,popc,96,"../../annotations/v3/figshare_10287393.json,....."
1,cholesterol,56,"../../annotations/v3/figshare_10287393.json,....."
2,dppc,52,"../../annotations/v3/figshare_2018634.json,../..."
3,nacl,46,"../../annotations/v3/figshare_20485017.json,....."
4,dmtap,28,"../../annotations/v3/zenodo_51747.json,../../a..."
...,...,...,...
1123,chloroform,1,../../annotations/v3/figshare_21806690.json
1124,cyclophane,1,../../annotations/v3/figshare_21806690.json
1125,polycyclic aromatic hydrocarbons,1,../../annotations/v3/figshare_21806690.json
1126,saccharides,1,../../annotations/v3/figshare_7607222.json
1127,phosphates,1,../../annotations/v3/figshare_1146536.json

In [24]:
total_entities = len(df)
rare_df = df[df["count"] == 1]
num_rare = len(rare_df)

print(f"Rare molecules (count = 1): {num_rare} / {total_entities} total entities")
rare_df

Rare molecules (count = 1): 587 / 1128 total entities

,entity,count,annotation_paths
541,mln-4760,1,../../annotations/v3/figshare_14156828.json
542,sars-cov‑2,1,../../annotations/v3/figshare_14156828.json
543,rna virus,1,../../annotations/v3/figshare_14156828.json
544,anti-sars-cov-2,1,../../annotations/v3/figshare_14156828.json
545,amps,1,../../annotations/v3/zenodo_7327525.json
...,...,...,...
1123,chloroform,1,../../annotations/v3/figshare_21806690.json
1124,cyclophane,1,../../annotations/v3/figshare_21806690.json
1125,polycyclic aromatic hydrocarbons,1,../../annotations/v3/figshare_21806690.json
1126,saccharides,1,../../annotations/v3/figshare_7607222.json
1127,phosphates,1,../../annotations/v3/figshare_1146536.json

## Force Field Model Name 🛠️

In [25]:
df = entity_data["FFM"].sort_values("count", ascending=False)
df

,entity,count,annotation_paths
0,charmm36,49,"../../annotations/v3/figshare_14225919.json,....."
1,martini,33,"../../annotations/v3/figshare_11569377.json,....."
2,amber,27,"../../annotations/v3/figshare_11688372.json,....."
3,tip3p,25,"../../annotations/v3/figshare_13135976.json,....."
4,charmm,24,"../../annotations/v3/figshare_14498668.json,....."
...,...,...,...
101,gromos54a7,1,../../annotations/v3/figshare_4806544.json
102,βol15,1,../../annotations/v3/figshare_19102457.json
103,charmm36 forcefield (version july 2020),1,../../annotations/v3/zenodo_7037843.json
104,autodock,1,../../annotations/v3/figshare_121241.json
105,gromos 56a6carbo/carbo_r,1,../../annotations/v3/figshare_7607222.json

In [26]:
total_entities = len(df)
rare_df = df[df["count"] == 1]
num_rare = len(rare_df)

print(
    f"Rare force field or model (count = 1): {num_rare} / {total_entities} total entities"
)
rare_df

Rare force field or model (count = 1): 49 / 106 total entities

,entity,count,annotation_paths
57,dang,1,../../annotations/v3/zenodo_3613573.json
58,ff03*,1,../../annotations/v3/figshare_2532337.json
59,ff03w,1,../../annotations/v3/figshare_2532337.json
60,ff99sb*,1,../../annotations/v3/figshare_2532337.json
61,ff99sb-ildn,1,../../annotations/v3/figshare_2532337.json
62,charmm tip3p,1,../../annotations/v3/zenodo_3988469.json
63,ff96,1,../../annotations/v3/figshare_2532337.json
64,ff99,1,../../annotations/v3/figshare_2532337.json
65,ff03,1,../../annotations/v3/figshare_2532337.json
66,amber10:extended huckel theory (eht),1,../../annotations/v3/zenodo_3988469.json
67,nb-fix,1,../../annotations/v3/zenodo_1198454.json
68,rsff1,1,../../annotations/v3/figshare_3207154.json
69,amoeba,1,../../annotations/v3/figshare_8258741.json
70,l-opls,1,../../annotations/v3/figshare_14225919.json
71,martini 3.0,1,../../annotations/v3/zenodo_6010416.json
72,tip4p/2005,1,../../annotations/v3/figshare_13836577.json
73,trappe-ua,1,../../annotations/v3/figshare_13836577.json
74,amber ff99sb-ildn,1,../../annotations/v3/zenodo_6349893.json
75,amber14sb,1,../../annotations/v3/zenodo_3975394.json
76,sl,1,../../annotations/v3/zenodo_7572990.json
77,c36,1,../../annotations/v3/zenodo_7572990.json
78,bind3p,1,../../annotations/v3/figshare_11808522.json
79,54a7,1,../../annotations/v3/figshare_11771604.json
80,martini 2.2p,1,../../annotations/v3/zenodo_6973476.json
81,amber ff15ipq,1,../../annotations/v3/zenodo_5497661.json
82,tip4p-ew,1,../../annotations/v3/figshare_12987701.json
83,q4md-cd,1,../../annotations/v3/figshare_11808522.json
84,amber14,1,../../annotations/v3/zenodo_4805388.json
85,gdml,1,../../annotations/v3/zenodo_7112198.json
86,"bpy1,3-tfsi",1,../../annotations/v3/zenodo_3696970.json
87,gap,1,../../annotations/v3/zenodo_7112198.json
88,schnet,1,../../annotations/v3/zenodo_7112198.json
89,amber ff99sb,1,../../annotations/v3/zenodo_6349893.json
90,parm99_lna,1,../../annotations/v3/figshare_19102457.json
91,ol15,1,../../annotations/v3/figshare_19102457.json
92,martini 3,1,../../annotations/v3/zenodo_5060102.json
93,charmm36mw,1,../../annotations/v3/zenodo_5573728.json
94,43a1-s3,1,../../annotations/v3/zenodo_1293762.json
95,martini coarse-grained (cg) force field (v. 2.2),1,../../annotations/v3/zenodo_3901180.json
96,opls-aa/m,1,../../annotations/v3/figshare_9941741.json
97,parmbsc0,1,../../annotations/v3/figshare_19102457.json
98,tip,1,../../annotations/v3/figshare_12064266.json
99,martini cg,1,../../annotations/v3/figshare_2154835.json
100,charmm 27,1,../../annotations/v3/figshare_3983526.json
101,gromos54a7,1,../../annotations/v3/figshare_4806544.json
102,βol15,1,../../annotations/v3/figshare_19102457.json
103,charmm36 forcefield (version july 2020),1,../../annotations/v3/zenodo_7037843.json
104,autodock,1,../../annotations/v3/figshare_121241.json
105,gromos 56a6carbo/carbo_r,1,../../annotations/v3/figshare_7607222.json

## Software name ⚙️

In [27]:
df = entity_data["SOFTNAME"].sort_values("count", ascending=False)
df

        entity  count                                   annotation_paths
0      gromacs    144  ../../annotations/v3/figshare_13116890.json,.....
1       lammps     21  ../../annotations/v3/figshare_16772812.json,.....
2        amber     16  ../../annotations/v3/figshare_12987701.json,.....
3          vmd     15  ../../annotations/v3/figshare_13352375.json,.....
4   charmm-gui     11  ../../annotations/v3/zenodo_1198158.json,../.....
..         ...    ...                                                ...
73       gibbs      1         ../../annotations/v3/figshare_2267512.json
74   swissprot      1           ../../annotations/v3/zenodo_4730896.json
75     maestro      1           ../../annotations/v3/zenodo_3362889.json
76      molpro      1           ../../annotations/v3/zenodo_6791151.json
77  gaussian16      1           ../../annotations/v3/zenodo_3361945.json

[78 rows x 3 columns]

In [28]:
total_entities = len(df)
rare_df = df[df["count"] == 1]
num_rare = len(rare_df)

print(f"Rare software names (count = 1): {num_rare} / {total_entities} total entities")
rare_df

Rare software names (count = 1): 38 / 78 total entities

,entity,count,annotation_paths
40,visual molecular dynamics,1,../../annotations/v3/zenodo_6879091.json
41,propka,1,../../annotations/v3/zenodo_6755131.json
42,pyinteraph,1,../../annotations/v3/zenodo_1346073.json
43,prmtop,1,../../annotations/v3/zenodo_6870476.json
44,charmm,1,../../annotations/v3/zenodo_2537734.json
45,jupyter,1,../../annotations/v3/zenodo_3865919.json
46,insane,1,../../annotations/v3/zenodo_1293813.json
47,pymol,1,../../annotations/v3/zenodo_6349893.json
48,paramchem,1,../../annotations/v3/zenodo_6988344.json
49,colvar,1,../../annotations/v3/zenodo_7323535.json
50,hoomd-blue,1,../../annotations/v3/zenodo_6957888.json
51,doglycans,1,../../annotations/v3/figshare_5496910.json
52,namd2,1,../../annotations/v3/zenodo_4245236.json
53,lipidbook,1,../../annotations/v3/zenodo_13392.json
54,deepmd-kit,1,../../annotations/v3/zenodo_7234728.json
55,glycam-web,1,../../annotations/v3/figshare_12272015.json
56,molsim,1,../../annotations/v3/zenodo_7523635.json
57,aimd,1,../../annotations/v3/zenodo_7234728.json
58,rosetta,1,../../annotations/v3/figshare_19082291.json
59,glycam,1,../../annotations/v3/zenodo_5592299.json
60,flexaid,1,../../annotations/v3/zenodo_2586559.json
61,rdock,1,../../annotations/v3/zenodo_2586559.json
62,optim,1,../../annotations/v3/zenodo_7107608.json
63,pathsample,1,../../annotations/v3/zenodo_7107608.json
64,cpptraj,1,../../annotations/v3/figshare_4757161.json
65,chimerax,1,../../annotations/v3/zenodo_7007107.json
66,pmemd,1,../../annotations/v3/figshare_4757161.json
67,intermol,1,../../annotations/v3/zenodo_5592299.json
68,alphafold,1,../../annotations/v3/zenodo_5642866.json
69,prody,1,../../annotations/v3/figshare_4806544.json
70,acemd,1,../../annotations/v3/figshare_3983526.json
71,unitymol,1,../../annotations/v3/zenodo_5060102.json
72,glide,1,../../annotations/v3/zenodo_3567651.json
73,gibbs,1,../../annotations/v3/figshare_2267512.json
74,swissprot,1,../../annotations/v3/zenodo_4730896.json
75,maestro,1,../../annotations/v3/zenodo_3362889.json
76,molpro,1,../../annotations/v3/zenodo_6791151.json
77,gaussian16,1,../../annotations/v3/zenodo_3361945.json

## Software version 🔢

In [29]:
df = entity_data["SOFTVERS"].sort_values("count", ascending=False)
df

,entity,count,annotation_paths
0,4.5,8,"../../annotations/v3/zenodo_13814.json,../../a..."
1,3.x,7,"../../annotations/v3/zenodo_51747.json,../../a..."
2,4.0.7,7,"../../annotations/v3/zenodo_1293762.json,../....."
3,5.1.4,4,"../../annotations/v3/zenodo_1118682.json,../....."
4,16,4,"../../annotations/v3/figshare_4757161.json,../..."
5,5.0.3,4,"../../annotations/v3/zenodo_30894.json,../../a..."
6,v. 2016.4,3,"../../annotations/v3/zenodo_3901180.json,../....."
7,v. 5.1,3,"../../annotations/v3/zenodo_1198158.json,../....."
8,2020,3,"../../annotations/v3/figshare_13352375.json,....."
9,19,2,../../annotations/v3/zenodo_3786821.json
10,v5,2,../../annotations/v3/zenodo_247386.json
11,2018.3,2,"../../annotations/v3/zenodo_3865919.json,../....."
12,21,2,../../annotations/v3/figshare_16574000.json
13,7,2,"../../annotations/v3/figshare_5247880.json,../..."
14,4,2,../../annotations/v3/zenodo_6592231.json
15,2016.1,2,"../../annotations/v3/zenodo_3228177.json,../....."
16,5.1.1,2,../../annotations/v3/zenodo_55565.json
17,2020.4,2,"../../annotations/v3/figshare_22182562.json,....."
18,version 2.6.0,1,../../annotations/v3/zenodo_3865919.json
19,4.6,1,../../annotations/v3/zenodo_259443.json
20,v.4.6.5,1,../../annotations/v3/figshare_13135976.json
21,v4.6,1,../../annotations/v3/zenodo_238943.json
22,2018,1,../../annotations/v3/zenodo_6755131.json
23,v9.16,1,../../annotations/v3/figshare_13135976.json
24,4.5.6,1,../../annotations/v3/zenodo_3236015.json
25,2016.2-dev-20170105-4feb0be,1,../../annotations/v3/zenodo_1219494.json
26,2018.0,1,../../annotations/v3/zenodo_1488094.json
27,"16 rev. b.01, 2016",1,../../annotations/v3/zenodo_7273800.json
28,"dec 2018, stable",1,../../annotations/v3/zenodo_7273800.json
29,16 rev b01,1,../../annotations/v3/zenodo_7273800.json
30,stable dec. 2018,1,../../annotations/v3/zenodo_7273800.json
31,2016.3,1,../../annotations/v3/zenodo_1167532.json
32,5.1.5,1,../../annotations/v3/zenodo_6973476.json
33,2021,1,../../annotations/v3/zenodo_7533587.json
34,version 2019.4,1,../../annotations/v3/zenodo_3667662.json
35,2.11b2,1,../../annotations/v3/zenodo_5497661.json
36,2021.4,1,../../annotations/v3/zenodo_7323535.json
37,v2.4,1,../../annotations/v3/zenodo_7533587.json
38,2018.1,1,../../annotations/v3/figshare_8003306.json
39,2019.3,1,../../annotations/v3/zenodo_6010416.json
40,2020.6,1,../../annotations/v3/zenodo_6349893.json
41,2023.2,1,../../annotations/v3/zenodo_17550324.json
42,5.1,1,../../annotations/v3/zenodo_573274.json
43,v. 2020,1,../../annotations/v3/zenodo_4300706.json
44,2.0,1,../../annotations/v3/zenodo_3696970.json
45,vina,1,../../annotations/v3/zenodo_2586559.json
46,5.0.x,1,../../annotations/v3/zenodo_838635.json
47,5.0.6,1,../../annotations/v3/zenodo_1293813.json
48,version 4.6,1,../../annotations/v3/figshare_5532214.json
49,2.6.3,1,../../annotations/v3/figshare_22182562.json
50,3.3.3,1,../../annotations/v3/figshare_4806544.json
51,5.1.x,1,../../annotations/v3/zenodo_6817824.json
52,v. 5.0,1,../../annotations/v3/zenodo_51185.json
53,1.9.3,1,../../annotations/v3/zenodo_4730896.json
54,2019,1,../../annotations/v3/zenodo_3592499.json
55,4.6.5,1,../../annotations/v3/zenodo_3908769.json

In [30]:
total_entities = len(df)
rare_df = df[df["count"] == 1]
num_rare = len(rare_df)

print(
    f"Rare software versions (count = 1): {num_rare} / {total_entities} total entities"
)
rare_df

Rare software versions (count = 1): 38 / 56 total entities

,entity,count,annotation_paths
18,version 2.6.0,1,../../annotations/v3/zenodo_3865919.json
19,4.6,1,../../annotations/v3/zenodo_259443.json
20,v.4.6.5,1,../../annotations/v3/figshare_13135976.json
21,v4.6,1,../../annotations/v3/zenodo_238943.json
22,2018,1,../../annotations/v3/zenodo_6755131.json
23,v9.16,1,../../annotations/v3/figshare_13135976.json
24,4.5.6,1,../../annotations/v3/zenodo_3236015.json
25,2016.2-dev-20170105-4feb0be,1,../../annotations/v3/zenodo_1219494.json
26,2018.0,1,../../annotations/v3/zenodo_1488094.json
27,"16 rev. b.01, 2016",1,../../annotations/v3/zenodo_7273800.json
28,"dec 2018, stable",1,../../annotations/v3/zenodo_7273800.json
29,16 rev b01,1,../../annotations/v3/zenodo_7273800.json
30,stable dec. 2018,1,../../annotations/v3/zenodo_7273800.json
31,2016.3,1,../../annotations/v3/zenodo_1167532.json
32,5.1.5,1,../../annotations/v3/zenodo_6973476.json
33,2021,1,../../annotations/v3/zenodo_7533587.json
34,version 2019.4,1,../../annotations/v3/zenodo_3667662.json
35,2.11b2,1,../../annotations/v3/zenodo_5497661.json
36,2021.4,1,../../annotations/v3/zenodo_7323535.json
37,v2.4,1,../../annotations/v3/zenodo_7533587.json
38,2018.1,1,../../annotations/v3/figshare_8003306.json
39,2019.3,1,../../annotations/v3/zenodo_6010416.json
40,2020.6,1,../../annotations/v3/zenodo_6349893.json
41,2023.2,1,../../annotations/v3/zenodo_17550324.json
42,5.1,1,../../annotations/v3/zenodo_573274.json
43,v. 2020,1,../../annotations/v3/zenodo_4300706.json
44,2.0,1,../../annotations/v3/zenodo_3696970.json
45,vina,1,../../annotations/v3/zenodo_2586559.json
46,5.0.x,1,../../annotations/v3/zenodo_838635.json
47,5.0.6,1,../../annotations/v3/zenodo_1293813.json
48,version 4.6,1,../../annotations/v3/figshare_5532214.json
49,2.6.3,1,../../annotations/v3/figshare_22182562.json
50,3.3.3,1,../../annotations/v3/figshare_4806544.json
51,5.1.x,1,../../annotations/v3/zenodo_6817824.json
52,v. 5.0,1,../../annotations/v3/zenodo_51185.json
53,1.9.3,1,../../annotations/v3/zenodo_4730896.json
54,2019,1,../../annotations/v3/zenodo_3592499.json
55,4.6.5,1,../../annotations/v3/zenodo_3908769.json

## Simulation time ⏱

In [31]:
df = entity_data["STIME"].sort_values("count", ascending=False)
df

         entity  count                                   annotation_paths
0         500ns     12  ../../annotations/v3/zenodo_1009027.json,../.....
1        500 ns      9  ../../annotations/v3/zenodo_17550324.json,../....
2         100ns      9  ../../annotations/v3/zenodo_14591.json,../../a...
3        200 ns      9  ../../annotations/v3/figshare_2527738.json,../...
4   microsecond      9  ../../annotations/v3/figshare_20376757.json,.....
..          ...    ...                                                ...
81       1.6 μs      1         ../../annotations/v3/figshare_5642866.json
82       380 ns      1           ../../annotations/v3/zenodo_1198158.json
83        500ps      1        ../../annotations/v3/figshare_11808396.json
84       500 ps      1        ../../annotations/v3/figshare_11808396.json
85         27ns      1           ../../annotations/v3/zenodo_3908769.json

[86 rows x 3 columns]

In [32]:
total_entities = len(df)
rare_df = df[df["count"] == 1]
num_rare = len(rare_df)

print(
    f"Rare simulation times (count = 1): {num_rare} / {total_entities} total entities"
)
rare_df

Rare simulation times (count = 1): 61 / 86 total entities

                entity  count                             annotation_paths
25              600 ns      1  ../../annotations/v3/figshare_20359967.json
26          nanosecond      1   ../../annotations/v3/figshare_2271034.json
27  hundred nanosecond      1  ../../annotations/v3/figshare_13135976.json
28     300 nanoseconds      1     ../../annotations/v3/zenodo_5153261.json
29              370 ns      1     ../../annotations/v3/zenodo_1198454.json
..                 ...    ...                                          ...
81              1.6 μs      1   ../../annotations/v3/figshare_5642866.json
82              380 ns      1     ../../annotations/v3/zenodo_1198158.json
83               500ps      1  ../../annotations/v3/figshare_11808396.json
84              500 ps      1  ../../annotations/v3/figshare_11808396.json
85                27ns      1     ../../annotations/v3/zenodo_3908769.json

[61 rows x 3 columns]

## Temperature 🌡️

In [33]:
df = entity_data["TEMP"].sort_values("count", ascending=False)
df

      entity  count                                   annotation_paths
0       310k     16  ../../annotations/v3/figshare_8046437.json,../...
1      310 k     14  ../../annotations/v3/figshare_11764158.json,.....
2      300 k     12  ../../annotations/v3/figshare_2615170.json,../...
3      298 k      7  ../../annotations/v3/figshare_20485017.json,.....
4      323 k      6  ../../annotations/v3/zenodo_51747.json,../../a...
5       325k      5  ../../annotations/v3/zenodo_1009027.json,../.....
6       288k      4  ../../annotations/v3/zenodo_3950029.json,../.....
7       323k      4  ../../annotations/v3/zenodo_14591.json,../../a...
8       303k      4  ../../annotations/v3/zenodo_1009607.json,../.....
9       358k      4  ../../annotations/v3/zenodo_3950029.json,../.....
10    298.15      3  ../../annotations/v3/zenodo_30894.json,../../a...
11   315.0 k      3           ../../annotations/v3/zenodo_5573728.json
12     313 k      3  ../../annotations/v3/zenodo_1118682.json,../.....
13  298.15 k      2           ../../annotations/v3/zenodo_7112198.json
14   318.0 k      2           ../../annotations/v3/zenodo_5573728.json
15    283.15      2        ../../annotations/v3/figshare_16698491.json
16      320k      2           ../../annotations/v3/zenodo_1009027.json
17   319.1 k      2           ../../annotations/v3/zenodo_5573728.json
18   316.0 k      2           ../../annotations/v3/zenodo_5573728.json
19   317.0 k      2           ../../annotations/v3/zenodo_5573728.json
20     363 k      2           ../../annotations/v3/zenodo_7007107.json
21      338k      2           ../../annotations/v3/zenodo_1009027.json
22  318.15 k      2        ../../annotations/v3/figshare_16698491.json
23      37°c      1           ../../annotations/v3/zenodo_3988469.json
24      2500      1           ../../annotations/v3/zenodo_7234728.json
25     340 k      1           ../../annotations/v3/zenodo_6380887.json
26     293 k      1            ../../annotations/v3/zenodo_259443.json
27     360 k      1           ../../annotations/v3/zenodo_6791876.json
28  295.15 k      1          ../../annotations/v3/zenodo_17550324.json
29     225 k      1           ../../annotations/v3/zenodo_4106413.json
30       200      1           ../../annotations/v3/zenodo_4106413.json
31      300k      1        ../../annotations/v3/figshare_16574000.json
32  273.15 k      1        ../../annotations/v3/figshare_12987701.json
33     210 k      1        ../../annotations/v3/figshare_12987701.json
34       242      1        ../../annotations/v3/figshare_12987701.json
35     365 k      1        ../../annotations/v3/figshare_16715821.json
36  473.15 k      1        ../../annotations/v3/figshare_13836577.json
37      298k      1           ../../annotations/v3/zenodo_1167532.json
38      3500      1           ../../annotations/v3/zenodo_7234728.json
39    4000 k      1           ../../annotations/v3/zenodo_7234728.json
40      3000      1           ../../annotations/v3/zenodo_7234728.json
41  310.15°k      1           ../../annotations/v3/zenodo_3988469.json
42       298      1           ../../annotations/v3/zenodo_2653735.json
43     130 k      1        ../../annotations/v3/figshare_22213635.json
44      322k      1           ../../annotations/v3/zenodo_1009027.json
45       315      1           ../../annotations/v3/zenodo_1009027.json
46     338 k      1           ../../annotations/v3/zenodo_1009027.json
47      315k      1           ../../annotations/v3/zenodo_1009027.json
48       310      1           ../../annotations/v3/zenodo_2653735.json
49       320      1           ../../annotations/v3/zenodo_2653735.json
50     333 k      1           ../../annotations/v3/zenodo_2653735.json
51    5000 k      1        ../../annotations/v3/figshare_12218135.json
52       285      1           ../../annotations/v3/zenodo_2653735.json
53   316.7 k      1           ../../annotations/v3/zenodo_5573728.json
54      363k      1           ../../annotations/v3/zenodo_7007107.json
55     90 ˚c      1           ../../annotations/v3/zenodo_7007107.json
56   318.4 k      1           ../../annotations/v3/zenodo_5573728.json
57   321.8 k      1           ../../annotations/v3/zenodo_5573728.json
58     295 k      1         ../../annotations/v3/figshare_4541035.json
59       303      1            ../../annotations/v3/zenodo_247386.json

In [34]:
total_entities = len(df)
rare_df = df[df["count"] == 1]
num_rare = len(rare_df)

print(f"Rare temperatures (count = 1): {num_rare} / {total_entities} total entities")
rare_df

Rare temperatures (count = 1): 37 / 60 total entities

      entity  count                             annotation_paths
23      37°c      1     ../../annotations/v3/zenodo_3988469.json
24      2500      1     ../../annotations/v3/zenodo_7234728.json
25     340 k      1     ../../annotations/v3/zenodo_6380887.json
26     293 k      1      ../../annotations/v3/zenodo_259443.json
27     360 k      1     ../../annotations/v3/zenodo_6791876.json
28  295.15 k      1    ../../annotations/v3/zenodo_17550324.json
29     225 k      1     ../../annotations/v3/zenodo_4106413.json
30       200      1     ../../annotations/v3/zenodo_4106413.json
31      300k      1  ../../annotations/v3/figshare_16574000.json
32  273.15 k      1  ../../annotations/v3/figshare_12987701.json
33     210 k      1  ../../annotations/v3/figshare_12987701.json
34       242      1  ../../annotations/v3/figshare_12987701.json
35     365 k      1  ../../annotations/v3/figshare_16715821.json
36  473.15 k      1  ../../annotations/v3/figshare_13836577.json
37      298k      1     ../../annotations/v3/zenodo_1167532.json
38      3500      1     ../../annotations/v3/zenodo_7234728.json
39    4000 k      1     ../../annotations/v3/zenodo_7234728.json
40      3000      1     ../../annotations/v3/zenodo_7234728.json
41  310.15°k      1     ../../annotations/v3/zenodo_3988469.json
42       298      1     ../../annotations/v3/zenodo_2653735.json
43     130 k      1  ../../annotations/v3/figshare_22213635.json
44      322k      1     ../../annotations/v3/zenodo_1009027.json
45       315      1     ../../annotations/v3/zenodo_1009027.json
46     338 k      1     ../../annotations/v3/zenodo_1009027.json
47      315k      1     ../../annotations/v3/zenodo_1009027.json
48       310      1     ../../annotations/v3/zenodo_2653735.json
49       320      1     ../../annotations/v3/zenodo_2653735.json
50     333 k      1     ../../annotations/v3/zenodo_2653735.json
51    5000 k      1  ../../annotations/v3/figshare_12218135.json
52       285      1     ../../annotations/v3/zenodo_2653735.json
53   316.7 k      1     ../../annotations/v3/zenodo_5573728.json
54      363k      1     ../../annotations/v3/zenodo_7007107.json
55     90 ˚c      1     ../../annotations/v3/zenodo_7007107.json
56   318.4 k      1     ../../annotations/v3/zenodo_5573728.json
57   321.8 k      1     ../../annotations/v3/zenodo_5573728.json
58     295 k      1   ../../annotations/v3/figshare_4541035.json
59       303      1      ../../annotations/v3/zenodo_247386.json