# **QC Entity Inventory Explorer 🧐**

This notebook allows exploration of QC entity inventory results generated
by `src/mdner_llm/utils/build_entity_vocab.py`.

We can inspect:

- The top entities per class
- Rare entities with low occurrences

The insights gained here will help define **rules for annotation**,
to be documented in [`docs/annotation_rules.md`](../docs/annotation_rules.md).

## Load libraries and setup

In [1]:
from pathlib import Path

from mdner_llm.utils.build_entity_vocab import process_qc_entity_inventory

In [2]:
%load_ext watermark
%watermark

Last updated: 2026-04-07T13:41:39.977594+02:00

Python implementation: CPython
Python version       : 3.13.0
IPython version      : 8.13.2

Compiler    : Clang 18.1.8
OS          : Linux
Release     : 6.8.0-51-generic
Machine     : x86_64
Processor   : x86_64
CPU cores   : 4
Architecture: 64bit

## Load data

In [3]:
# Define the annotation directory
annotations_path = Path("../../results/groundtruth_paths.txt")
# Define the results directory
results_path = Path("../../results/qc_annotations/entities.tsv")

In [4]:
# Process the QC entity inventory
# Get dictionnary containing entity counts for each class label
entity_data = process_qc_entity_inventory(annotations_path, results_path)

2026-04-07 13:41:40 | INFO     | Starting QC entity inventory.
2026-04-07 13:41:40 | INFO     | Collecting entity counts.
2026-04-07 13:41:40 | INFO     | Reading list of JSON files from ../../results/groundtruth_paths.txt.
2026-04-07 13:41:40 | SUCCESS  | Found 109 JSON files successfully.
2026-04-07 13:41:40 | SUCCESS  | Collected entity counts for 6 classes: FFM, MOL, SOFTNAME, SOFTVERS, STIME, TEMP!
2026-04-07 13:41:40 | INFO     | Writing global entity TSV file.
2026-04-07 13:41:41 | SUCCESS  | Saved global entity TSV file to ../../results/qc_annotations/entities.tsv successfully!
2026-04-07 13:41:41 | SUCCESS  | QC entity inventory completed successfully!

In [5]:
print("Annotation summary by class:")
print("-" * 50)
print(f"{'Class':20} | {'Total occurrences':17} | {'Unique entities':15}")
print("-" * 50)

# Trier par total_occurrences décroissant
for class_name, df in sorted(
    entity_data.items(), key=lambda x: x[1]["count"].sum(), reverse=True
):
    total_occurrences = df["count"].sum()
    unique_entities = df.shape[0]
    print(f"{class_name:20} | {total_occurrences:17} | {unique_entities:15}")

print("-" * 50)

Annotation summary by class:
--------------------------------------------------
Class                | Total occurrences | Unique entities
--------------------------------------------------
MOL                  |              1044 |             398
FFM                  |               239 |              84
SOFTNAME             |               161 |              38
STIME                |               115 |              62
TEMP                 |                92 |              39
SOFTVERS             |                57 |              39
--------------------------------------------------

##

## Molecules 🧬

In [6]:
df = entity_data["MOL"].sort_values("count", ascending=False)
df

,entity,count,annotation_paths
0,popc,64,"figshare_4806544.json,zenodo_1009607.json,zeno..."
1,dppc,36,"zenodo_1009027.json,zenodo_1009607.json,zenodo..."
2,nacl,32,"figshare_20485017.json,figshare_20485059.json,..."
3,cholesterol,25,"figshare_14994624.json,figshare_4806544.json,z..."
4,meth,18,figshare_11704443.json
...,...,...,...
393,grpnlkllllllgvllgvlltllllllleyp,1,zenodo_573274.json
394,aaaqaaqaqwaqrqatwqa,1,figshare_8046437.json
395,grpnlklllllllllgvllgvlltlllllllllleyp,1,zenodo_573274.json
396,polyleucine dimer,1,zenodo_573274.json
397,ca,1,zenodo_34415.json

In [7]:
total_entities = len(df)
rare_df = df[df["count"] == 1]
num_rare = len(rare_df)

print(f"Rare molecules (count = 1): {num_rare} / {total_entities} total entities")
rare_df

Rare molecules (count = 1): 208 / 398 total entities

                                    entity  count       annotation_paths
190                                    sol      1    zenodo_1219494.json
191                                     na      1    zenodo_1219494.json
192           basket-type dna g-quadruplex      1    zenodo_6791876.json
193                                   2kf7      1    zenodo_6791876.json
194                                   sdpc      1    zenodo_2645909.json
..                                     ...    ...                    ...
393        grpnlkllllllgvllgvlltllllllleyp      1     zenodo_573274.json
394                    aaaqaaqaqwaqrqatwqa      1  figshare_8046437.json
395  grpnlklllllllllgvllgvlltlllllllllleyp      1     zenodo_573274.json
396                      polyleucine dimer      1     zenodo_573274.json
397                                     ca      1      zenodo_34415.json

[208 rows x 3 columns]

## Force Field Model Name 🛠️

In [8]:
df = entity_data["FFM"].sort_values("count", ascending=False)
df

,entity,count,annotation_paths
0,charmm36,41,"figshare_14225919.json,zenodo_1009027.json,zen..."
1,tip3p,20,"figshare_13135976.json,figshare_20485017.json,..."
2,charmm,13,"figshare_14498668.json,figshare_22203473.json,..."
3,slipids,8,"zenodo_1293813.json,zenodo_259443.json,zenodo_..."
4,gaff,8,"figshare_121241.json,figshare_14766557.json,fi..."
...,...,...,...
79,nb-fix,1,zenodo_1198454.json
80,rsff1,1,figshare_3207154.json
81,gromos 56a6carbo/carbo_r,1,figshare_7607222.json
82,"bpy1,3-tfsi",1,zenodo_3696970.json
83,amber ff15ipq,1,zenodo_5497661.json

In [9]:
total_entities = len(df)
rare_df = df[df["count"] == 1]
num_rare = len(rare_df)

print(
    f"Rare force field or model (count = 1): {num_rare} / {total_entities} total entities"
)
rare_df

Rare force field or model (count = 1): 40 / 84 total entities

                                  entity  count        annotation_paths
44                             amber14sb      1     zenodo_3975394.json
45                            gromos54a7      1   figshare_4806544.json
46                           gromos 54a7      1   figshare_8046437.json
47                               43a1-s3      1     zenodo_1293762.json
48         generalized amber force field      1  figshare_14766557.json
49                             charmm 27      1   figshare_3983526.json
50                     amber ff99sb-ildn      1     zenodo_6349893.json
51                             martini 3      1     zenodo_5060102.json
52                                   c36      1     zenodo_7572990.json
53                            tip4p/2005      1  figshare_13836577.json
54                             trappe-ua      1  figshare_13836577.json
55                              gromos87      1     zenodo_6380887.json
56                          amber ff14sb      1   figshare_6575438.json
57                                  dang      1     zenodo_3613573.json
58                                 βol15      1  figshare_19102457.json
59                              parmbsc0      1  figshare_19102457.json
60                                  ol15      1  figshare_19102457.json
61                            parm99_lna      1  figshare_19102457.json
62                                  54a7      1  figshare_11771604.json
63                          amber ff99sb      1     zenodo_6349893.json
64               charmm36 (v. june 2015)      1     zenodo_3950029.json
65                               ff99sb*      1   figshare_2532337.json
66                           ff99sb-ildn      1   figshare_2532337.json
67                                    sl      1     zenodo_7572990.json
68                           martini 3.0      1     zenodo_6010416.json
69                                  ff96      1   figshare_2532337.json
70                                  ff99      1   figshare_2532337.json
71                                  ff03      1   figshare_2532337.json
72                                 ff03*      1   figshare_2532337.json
73                                 ff03w      1   figshare_2532337.json
74  amber10:extended huckel theory (eht)      1     zenodo_3988469.json
75                              autodock      1    figshare_121241.json
76                                l-opls      1  figshare_14225919.json
77                          charmm tip3p      1     zenodo_3988469.json
78                            charmm c36      1     zenodo_3988469.json
79                                nb-fix      1     zenodo_1198454.json
80                                 rsff1      1   figshare_3207154.json
81              gromos 56a6carbo/carbo_r      1   figshare_7607222.json
82                           bpy1,3-tfsi      1     zenodo_3696970.json
83                         amber ff15ipq      1     zenodo_5497661.json

## Software name ⚙️

In [10]:
df = entity_data["SOFTNAME"].sort_values("count", ascending=False)
df

,entity,count,annotation_paths
0,gromacs,82,"figshare_13135976.json,figshare_14498668.json,..."
1,charmm-gui,11,"zenodo_1198158.json,zenodo_2645909.json,zenodo..."
2,vmd,7,"figshare_14511885.json,zenodo_5060102.json,zen..."
3,plumed,6,"figshare_22182562.json,zenodo_3865919.json,zen..."
4,namd,4,"figshare_14498668.json,zenodo_3696970.json,zen..."
5,mdanalysis,4,"figshare_8046437.json,zenodo_5060102.json,zeno..."
6,modeller,4,"figshare_13135976.json,zenodo_6970327.json"
7,moe,3,zenodo_3988469.json
8,colabfold,3,zenodo_6970327.json
9,ani2x,3,zenodo_5060102.json
10,pydock,2,zenodo_5153261.json
11,bumpy,2,"zenodo_4196842.json,zenodo_4445375.json"
12,ase,2,zenodo_5060102.json
13,amber,2,"zenodo_3988469.json,zenodo_6755131.json"
14,colvar,2,zenodo_7323535.json
15,torchani,2,zenodo_5060102.json
16,insane,1,zenodo_1293813.json
17,prody,1,figshare_4806544.json
18,pymol,1,zenodo_6349893.json
19,openmm,1,zenodo_1118682.json
20,propka,1,zenodo_6755131.json
21,antechamber,1,zenodo_6755131.json
22,acemd,1,figshare_3983526.json
23,hoomd-blue,1,zenodo_6957888.json
24,unitymol,1,zenodo_5060102.json
25,chimerax,1,zenodo_7007107.json
26,optim,1,zenodo_7107608.json
27,pathsample,1,zenodo_7107608.json
28,paramchem,1,zenodo_6988344.json
29,jupyter,1,zenodo_3865919.json
30,visual molecular dynamics,1,zenodo_6879091.json
31,ambertools,1,zenodo_7107608.json
32,maestro,1,zenodo_3362889.json
33,desmond,1,zenodo_3362889.json
34,gaussian09,1,zenodo_3696970.json
35,galaxy,1,zenodo_2537734.json
36,bridge,1,zenodo_2537734.json
37,charmm,1,zenodo_2537734.json

In [11]:
total_entities = len(df)
rare_df = df[df["count"] == 1]
num_rare = len(rare_df)

print(f"Rare software names (count = 1): {num_rare} / {total_entities} total entities")
rare_df

Rare software names (count = 1): 22 / 38 total entities

                       entity  count       annotation_paths
16                     insane      1    zenodo_1293813.json
17                      prody      1  figshare_4806544.json
18                      pymol      1    zenodo_6349893.json
19                     openmm      1    zenodo_1118682.json
20                     propka      1    zenodo_6755131.json
21                antechamber      1    zenodo_6755131.json
22                      acemd      1  figshare_3983526.json
23                 hoomd-blue      1    zenodo_6957888.json
24                   unitymol      1    zenodo_5060102.json
25                   chimerax      1    zenodo_7007107.json
26                      optim      1    zenodo_7107608.json
27                 pathsample      1    zenodo_7107608.json
28                  paramchem      1    zenodo_6988344.json
29                    jupyter      1    zenodo_3865919.json
30  visual molecular dynamics      1    zenodo_6879091.json
31                 ambertools      1    zenodo_7107608.json
32                    maestro      1    zenodo_3362889.json
33                    desmond      1    zenodo_3362889.json
34                 gaussian09      1    zenodo_3696970.json
35                     galaxy      1    zenodo_2537734.json
36                     bridge      1    zenodo_2537734.json
37                     charmm      1    zenodo_2537734.json

## Software version 🔢

In [12]:
df = entity_data["SOFTVERS"].sort_values("count", ascending=False)
df

,entity,count,annotation_paths
0,4.5,7,"zenodo_13814.json,zenodo_13853.json,zenodo_155..."
1,4.0.7,3,"zenodo_1293762.json,zenodo_14591.json"
2,5.1.4,3,"zenodo_1118682.json,zenodo_1198158.json,zenodo..."
3,3.x,2,"zenodo_51750.json,zenodo_53212.json"
4,v5,2,zenodo_247386.json
5,2016.3,2,zenodo_1167532.json
6,5.0.3,2,"zenodo_30904.json,zenodo_34415.json"
7,2021.4,2,zenodo_7323535.json
8,2020.4,2,"figshare_22182562.json,zenodo_7007107.json"
9,19,2,zenodo_3786821.json
10,v. 5.1,2,"zenodo_1198158.json,zenodo_1198454.json"
11,3.3.3,1,figshare_4806544.json
12,5.0.x,1,zenodo_838635.json
13,2016.2-dev-20170105-4feb0be,1,zenodo_1219494.json
14,7,1,zenodo_1118682.json
15,2020.6,1,zenodo_6349893.json
16,2018.0,1,zenodo_1488094.json
17,2018,1,zenodo_6755131.json
18,v. 2016.4,1,zenodo_3950029.json
19,4.6,1,zenodo_259443.json
20,v. 5.0,1,zenodo_51185.json
21,2016.1,1,zenodo_3228177.json
22,5.0.6,1,zenodo_1293813.json
23,version 4.6,1,figshare_5532214.json
24,2019,1,zenodo_3592499.json
25,version 2.6.0,1,zenodo_3865919.json
26,2018.3,1,zenodo_3865919.json
27,2019.3,1,zenodo_6010416.json
28,5.1.x,1,zenodo_6817824.json
29,2023.2,1,zenodo_17550324.json
30,16,1,zenodo_3988469.json
31,v.4.6.5,1,figshare_13135976.json
32,v9.16,1,figshare_13135976.json
33,4.6.5,1,zenodo_3908769.json
34,2018.1,1,figshare_8003306.json
35,2.6.3,1,figshare_22182562.json
36,2.0,1,zenodo_3696970.json
37,2.11b2,1,zenodo_5497661.json
38,5.1,1,zenodo_573274.json

In [13]:
total_entities = len(df)
rare_df = df[df["count"] == 1]
num_rare = len(rare_df)

print(
    f"Rare software versions (count = 1): {num_rare} / {total_entities} total entities"
)
rare_df

Rare software versions (count = 1): 28 / 39 total entities

                         entity  count        annotation_paths
11                        3.3.3      1   figshare_4806544.json
12                        5.0.x      1      zenodo_838635.json
13  2016.2-dev-20170105-4feb0be      1     zenodo_1219494.json
14                            7      1     zenodo_1118682.json
15                       2020.6      1     zenodo_6349893.json
16                       2018.0      1     zenodo_1488094.json
17                         2018      1     zenodo_6755131.json
18                    v. 2016.4      1     zenodo_3950029.json
19                          4.6      1      zenodo_259443.json
20                       v. 5.0      1       zenodo_51185.json
21                       2016.1      1     zenodo_3228177.json
22                        5.0.6      1     zenodo_1293813.json
23                  version 4.6      1   figshare_5532214.json
24                         2019      1     zenodo_3592499.json
25                version 2.6.0      1     zenodo_3865919.json
26                       2018.3      1     zenodo_3865919.json
27                       2019.3      1     zenodo_6010416.json
28                        5.1.x      1     zenodo_6817824.json
29                       2023.2      1    zenodo_17550324.json
30                           16      1     zenodo_3988469.json
31                      v.4.6.5      1  figshare_13135976.json
32                        v9.16      1  figshare_13135976.json
33                        4.6.5      1     zenodo_3908769.json
34                       2018.1      1   figshare_8003306.json
35                        2.6.3      1  figshare_22182562.json
36                          2.0      1     zenodo_3696970.json
37                       2.11b2      1     zenodo_5497661.json
38                          5.1      1      zenodo_573274.json

## Simulation time ⏱

In [14]:
df = entity_data["STIME"].sort_values("count", ascending=False)
df

,entity,count,annotation_paths
0,500ns,12,"zenodo_1009027.json,zenodo_1009607.json"
1,200 ns,8,"figshare_4806544.json,zenodo_1118682.json,zeno..."
2,500 ns,8,"zenodo_17550324.json,zenodo_259443.json,zenodo..."
3,100 ns,6,"figshare_22182562.json,zenodo_247386.json,zeno..."
4,1 microsecond,6,"figshare_20485017.json,figshare_20485059.json,..."
...,...,...,...
57,hundred nanosecond,1,figshare_13135976.json
58,one hundred nanosecond,1,figshare_13135976.json
59,27ns,1,zenodo_3908769.json
60,300 ns,1,zenodo_6144286.json
61,4-microsecond,1,zenodo_2645909.json

In [15]:
total_entities = len(df)
rare_df = df[df["count"] == 1]
num_rare = len(rare_df)

print(
    f"Rare simulation times (count = 1): {num_rare} / {total_entities} total entities"
)
rare_df

Rare simulation times (count = 1): 45 / 62 total entities

                    entity  count        annotation_paths
17         10 microseconds      1     zenodo_3975394.json
18                    40ns      1       zenodo_13853.json
19                  380 ns      1     zenodo_1198158.json
20              100–200 ns      1      zenodo_838635.json
21                   11 ns      1       zenodo_51750.json
22           1.5 micro-sec      1     zenodo_6349893.json
23                    50ns      1       zenodo_15550.json
24           6microseconds      1     zenodo_3975394.json
25                   10 ns      1     zenodo_5060102.json
26                  125 ns      1     zenodo_7007107.json
27                  110 ns      1       zenodo_51750.json
28                    1 ns      1   figshare_8046437.json
29                 1069 ns      1     zenodo_1219494.json
30                    3 μs      1     zenodo_7007107.json
31                  250 ns      1     zenodo_7007107.json
32                   80 ns      1     zenodo_7007107.json
33                  800 ns      1      zenodo_259443.json
34                  190 ns      1       zenodo_53212.json
35                  1.6 ns      1  figshare_20376757.json
36                     6µs      1   figshare_3983526.json
37                   12 μs      1     zenodo_7007107.json
38                    60ns      1       zenodo_13814.json
39                    298k      1       zenodo_13814.json
40                 4200 ns      1     zenodo_3228177.json
41                  0.5 μs      1     zenodo_4106413.json
42          8 microseconds      1     zenodo_5226209.json
43           5-microsecond      1   figshare_5532214.json
44                    1 μs      1   figshare_5546158.json
45                  450 ns      1   figshare_6575438.json
46               100-200ns      1     zenodo_7572990.json
47               200-300ns      1     zenodo_7572990.json
48                   120ns      1       zenodo_44622.json
49                    5 μs      1   figshare_9788852.json
50                   20 ns      1    figshare_121241.json
51                   500ps      1  figshare_11808396.json
52                  500 ps      1  figshare_11808396.json
53                 5000 ns      1     zenodo_6817824.json
54                  150 ns      1     zenodo_3988469.json
55         300 nanoseconds      1     zenodo_5153261.json
56                  370 ns      1     zenodo_1198454.json
57      hundred nanosecond      1  figshare_13135976.json
58  one hundred nanosecond      1  figshare_13135976.json
59                    27ns      1     zenodo_3908769.json
60                  300 ns      1     zenodo_6144286.json
61           4-microsecond      1     zenodo_2645909.json

## Temperature 🌡️

In [16]:
df = entity_data["TEMP"].sort_values("count", ascending=False)
df

      entity  count                                   annotation_paths
0       310k     13  figshare_8046437.json,zenodo_1009607.json,zeno...
1      310 k     12  figshare_11808396.json,figshare_13135976.json,...
2      298 k      7  figshare_20485017.json,figshare_20485059.json,...
3      300 k      7  figshare_2615170.json,figshare_4806544.json,ze...
4       325k      5            zenodo_1009027.json,zenodo_1009607.json
5       303k      4  zenodo_1009607.json,zenodo_13853.json,zenodo_2...
6      313 k      3            zenodo_1118682.json,zenodo_1293762.json
7       323k      2                zenodo_14591.json,zenodo_15550.json
8      323 k      2                zenodo_51750.json,zenodo_53212.json
9       358k      2                                zenodo_3950029.json
10      288k      2                                zenodo_3950029.json
11      320k      2                                zenodo_1009027.json
12    298.15      2                zenodo_30904.json,zenodo_34415.json
13      298k      2                                zenodo_1167532.json
14      338k      2                                zenodo_1009027.json
15     363 k      2                                zenodo_7007107.json
16      315k      1                                zenodo_1009027.json
17     338 k      1                                zenodo_1009027.json
18       315      1                                zenodo_1009027.json
19      322k      1                                zenodo_1009027.json
20     333 k      1                                zenodo_2653735.json
21       285      1                                zenodo_2653735.json
22       298      1                                zenodo_2653735.json
23       303      1                                 zenodo_247386.json
24       310      1                                zenodo_2653735.json
25       320      1                                zenodo_2653735.json
26      363k      1                                zenodo_7007107.json
27     90 ˚c      1                                zenodo_7007107.json
28     293 k      1                                 zenodo_259443.json
29     130 k      1                             figshare_22213635.json
30       200      1                                zenodo_4106413.json
31     225 k      1                                zenodo_4106413.json
32     340 k      1                                zenodo_6380887.json
33  473.15 k      1                             figshare_13836577.json
34     295 k      1                              figshare_4541035.json
35  295.15 k      1                               zenodo_17550324.json
36  310.15°k      1                                zenodo_3988469.json
37      37°c      1                                zenodo_3988469.json
38     360 k      1                                zenodo_6791876.json

In [17]:
total_entities = len(df)
rare_df = df[df["count"] == 1]
num_rare = len(rare_df)

print(f"Rare temperatures (count = 1): {num_rare} / {total_entities} total entities")
rare_df

Rare temperatures (count = 1): 23 / 39 total entities

      entity  count        annotation_paths
16      315k      1     zenodo_1009027.json
17     338 k      1     zenodo_1009027.json
18       315      1     zenodo_1009027.json
19      322k      1     zenodo_1009027.json
20     333 k      1     zenodo_2653735.json
21       285      1     zenodo_2653735.json
22       298      1     zenodo_2653735.json
23       303      1      zenodo_247386.json
24       310      1     zenodo_2653735.json
25       320      1     zenodo_2653735.json
26      363k      1     zenodo_7007107.json
27     90 ˚c      1     zenodo_7007107.json
28     293 k      1      zenodo_259443.json
29     130 k      1  figshare_22213635.json
30       200      1     zenodo_4106413.json
31     225 k      1     zenodo_4106413.json
32     340 k      1     zenodo_6380887.json
33  473.15 k      1  figshare_13836577.json
34     295 k      1   figshare_4541035.json
35  295.15 k      1    zenodo_17550324.json
36  310.15°k      1     zenodo_3988469.json
37      37°c      1     zenodo_3988469.json
38     360 k      1     zenodo_6791876.json