# List entities

This notebook allows exploration annotated entities

## Load libraries and setup

In [52]:
from pathlib import Path

import pandas as pd

In [53]:
%load_ext watermark
%watermark

The watermark extension is already loaded. To reload it, use:
  %reload_ext watermark
Last updated: 2026-04-08T14:15:18.517794+02:00

Python implementation: CPython
Python version       : 3.13.11
IPython version      : 8.13.2

Compiler    : GCC 14.3.0
OS          : Linux
Release     : 6.17.0-19-generic
Machine     : x86_64
Processor   : x86_64
CPU cores   : 14
Architecture: 64bit

## Load data

In [3]:
# Define the annotation directory
annotations_path = Path("../../results/groundtruth_paths.txt")
# Define the results directory
results_path = Path("../../results/qc_annotations/entities.tsv")

In [6]:
# Process the QC entity inventory
# Get dictionnary containing entity counts for each class label
entity_data = process_qc_entity_inventory(annotations_path, results_path)

2026-04-08 09:54:59 | INFO     | Starting QC entity inventory.
2026-04-08 09:54:59 | INFO     | Collecting entity counts.
2026-04-08 09:54:59 | INFO     | Reading list of JSON files from ../../results/groundtruth_paths.txt.
2026-04-08 09:54:59 | SUCCESS  | Found 109 JSON files successfully.
2026-04-08 09:54:59 | SUCCESS  | Collected entity counts for 6 classes: FFM, MOL, SOFTNAME, SOFTVERS, STIME, TEMP!
2026-04-08 09:54:59 | INFO     | Writing global entity TSV file.
2026-04-08 09:54:59 | SUCCESS  | Saved global entity TSV file to ../../results/qc_annotations/entities.tsv successfully!
2026-04-08 09:54:59 | SUCCESS  | QC entity inventory completed successfully!

In [34]:
entities_df = pd.read_csv(results_path, sep="\t").rename(columns={"class": "category"})
entities_df["number_of_files"] = entities_df["annotation_files"].str.count("json")
entities_df

,category,entity,occurrence,annotation_files,number_of_files
0,SOFTNAME,gromacs,82,"figshare_13135976.json,figshare_14498668.json,...",54
1,MOL,popc,64,"figshare_4806544.json,zenodo_1009607.json,zeno...",26
2,FFM,charmm36,41,"figshare_14225919.json,zenodo_1009027.json,zen...",21
3,MOL,dppc,36,"zenodo_1009027.json,zenodo_1009607.json,zenodo...",11
4,MOL,nacl,32,"figshare_20485017.json,figshare_20485059.json,...",15
...,...,...,...,...,...
655,STIME,hundred nanosecond,1,figshare_13135976.json,1
656,STIME,370 ns,1,zenodo_1198454.json,1
657,STIME,300 nanoseconds,1,zenodo_5153261.json,1
658,STIME,150 ns,1,zenodo_3988469.json,1
659,STIME,5000 ns,1,zenodo_6817824.json,1

In [30]:
entities_agg = (entities_df
 .groupby("category")
 .agg(
     total_entities=("occurrence", "sum"),
     unique_entities=("entity", "nunique")
 )
 .sort_values(by="total_entities", ascending=False)
)
entities_agg.loc["total"] = entities_agg.sum(numeric_only=True)
entities_agg

          total_entities  unique_entities
category
MOL                 1044              398
FFM                  239               84
SOFTNAME             161               38
STIME                115               62
TEMP                  92               39
SOFTVERS              57               39
total               1708              660

In [43]:
def list_entities(df, category):
    return (df
     .query("category == @category")
     .sort_values("occurrence", ascending=False)
     .reset_index(drop=True)
    )

## Molecules 🧬

In [44]:
list_entities(entities_df, "MOL")

,category,entity,occurrence,annotation_files,number_of_files
0,MOL,popc,64,"figshare_4806544.json,zenodo_1009607.json,zeno...",26
1,MOL,dppc,36,"zenodo_1009027.json,zenodo_1009607.json,zenodo...",11
2,MOL,nacl,32,"figshare_20485017.json,figshare_20485059.json,...",15
3,MOL,cholesterol,25,"figshare_14994624.json,figshare_4806544.json,z...",10
4,MOL,meth,18,figshare_11704443.json,1
...,...,...,...,...,...
393,MOL,crd,1,zenodo_17550324.json,1
394,MOL,carbohydrate recognition domain,1,zenodo_17550324.json,1
395,MOL,chl1,1,zenodo_6817824.json,1
396,MOL,hydrogenated alcohols,1,figshare_21726720.json,1
397,MOL,"1h,1h-perfluorinated alcohols",1,figshare_21726720.json,1

## Force Field Model Name 🛠️

In [45]:
list_entities(entities_df, "FFM")

,category,entity,occurrence,annotation_files,number_of_files
0,FFM,charmm36,41,"figshare_14225919.json,zenodo_1009027.json,zen...",21
1,FFM,tip3p,20,"figshare_13135976.json,figshare_20485017.json,...",19
2,FFM,charmm,13,"figshare_14498668.json,figshare_22203473.json,...",6
3,FFM,gaff,8,"figshare_121241.json,figshare_14766557.json,fi...",4
4,FFM,slipids,8,"zenodo_1293813.json,zenodo_259443.json,zenodo_...",4
...,...,...,...,...,...
79,FFM,charmm c36,1,zenodo_3988469.json,1
80,FFM,amber10:extended huckel theory (eht),1,zenodo_3988469.json,1
81,FFM,autodock,1,figshare_121241.json,1
82,FFM,amber ff15ipq,1,zenodo_5497661.json,1
83,FFM,"bpy1,3-tfsi",1,zenodo_3696970.json,1

## Software name ⚙️

In [51]:
list_entities(entities_df, "SOFTNAME")

,category,entity,occurrence,annotation_files,number_of_files
0,SOFTNAME,gromacs,82,"figshare_13135976.json,figshare_14498668.json,...",54
1,SOFTNAME,charmm-gui,11,"zenodo_1198158.json,zenodo_2645909.json,zenodo...",11
2,SOFTNAME,vmd,7,"figshare_14511885.json,zenodo_5060102.json,zen...",4
3,SOFTNAME,plumed,6,"figshare_22182562.json,zenodo_3865919.json,zen...",3
4,SOFTNAME,mdanalysis,4,"figshare_8046437.json,zenodo_5060102.json,zeno...",3
5,SOFTNAME,namd,4,"figshare_14498668.json,zenodo_3696970.json,zen...",3
6,SOFTNAME,modeller,4,"figshare_13135976.json,zenodo_6970327.json",2
7,SOFTNAME,ani2x,3,zenodo_5060102.json,1
8,SOFTNAME,moe,3,zenodo_3988469.json,1
9,SOFTNAME,colabfold,3,zenodo_6970327.json,1
10,SOFTNAME,bumpy,2,"zenodo_4196842.json,zenodo_4445375.json",2
11,SOFTNAME,ase,2,zenodo_5060102.json,1
12,SOFTNAME,torchani,2,zenodo_5060102.json,1
13,SOFTNAME,colvar,2,zenodo_7323535.json,1
14,SOFTNAME,amber,2,"zenodo_3988469.json,zenodo_6755131.json",2
15,SOFTNAME,pydock,2,zenodo_5153261.json,1
16,SOFTNAME,paramchem,1,zenodo_6988344.json,1
17,SOFTNAME,acemd,1,figshare_3983526.json,1
18,SOFTNAME,hoomd-blue,1,zenodo_6957888.json,1
19,SOFTNAME,chimerax,1,zenodo_7007107.json,1
20,SOFTNAME,unitymol,1,zenodo_5060102.json,1
21,SOFTNAME,pymol,1,zenodo_6349893.json,1
22,SOFTNAME,antechamber,1,zenodo_6755131.json,1
23,SOFTNAME,propka,1,zenodo_6755131.json,1
24,SOFTNAME,openmm,1,zenodo_1118682.json,1
25,SOFTNAME,insane,1,zenodo_1293813.json,1
26,SOFTNAME,prody,1,figshare_4806544.json,1
27,SOFTNAME,desmond,1,zenodo_3362889.json,1
28,SOFTNAME,maestro,1,zenodo_3362889.json,1
29,SOFTNAME,visual molecular dynamics,1,zenodo_6879091.json,1
30,SOFTNAME,ambertools,1,zenodo_7107608.json,1
31,SOFTNAME,pathsample,1,zenodo_7107608.json,1
32,SOFTNAME,optim,1,zenodo_7107608.json,1
33,SOFTNAME,jupyter,1,zenodo_3865919.json,1
34,SOFTNAME,charmm,1,zenodo_2537734.json,1
35,SOFTNAME,bridge,1,zenodo_2537734.json,1
36,SOFTNAME,galaxy,1,zenodo_2537734.json,1
37,SOFTNAME,gaussian09,1,zenodo_3696970.json,1

## Software version 🔢

In [48]:
list_entities(entities_df, "SOFTVERS")

,category,entity,occurrence,annotation_files,number_of_files
0,SOFTVERS,4.5,7,"zenodo_13814.json,zenodo_13853.json,zenodo_155...",4
1,SOFTVERS,4.0.7,3,"zenodo_1293762.json,zenodo_14591.json",2
2,SOFTVERS,5.1.4,3,"zenodo_1118682.json,zenodo_1198158.json,zenodo...",3
3,SOFTVERS,3.x,2,"zenodo_51750.json,zenodo_53212.json",2
4,SOFTVERS,2016.3,2,zenodo_1167532.json,1
5,SOFTVERS,5.0.3,2,"zenodo_30904.json,zenodo_34415.json",2
6,SOFTVERS,19,2,zenodo_3786821.json,1
7,SOFTVERS,2020.4,2,"figshare_22182562.json,zenodo_7007107.json",2
8,SOFTVERS,2021.4,2,zenodo_7323535.json,1
9,SOFTVERS,v5,2,zenodo_247386.json,1
10,SOFTVERS,v. 5.1,2,"zenodo_1198158.json,zenodo_1198454.json",2
11,SOFTVERS,5.0.6,1,zenodo_1293813.json,1
12,SOFTVERS,3.3.3,1,figshare_4806544.json,1
13,SOFTVERS,5.0.x,1,zenodo_838635.json,1
14,SOFTVERS,2016.2-dev-20170105-4feb0be,1,zenodo_1219494.json,1
15,SOFTVERS,16,1,zenodo_3988469.json,1
16,SOFTVERS,2023.2,1,zenodo_17550324.json,1
17,SOFTVERS,5.1.x,1,zenodo_6817824.json,1
18,SOFTVERS,2019.3,1,zenodo_6010416.json,1
19,SOFTVERS,2018.3,1,zenodo_3865919.json,1
20,SOFTVERS,version 2.6.0,1,zenodo_3865919.json,1
21,SOFTVERS,2019,1,zenodo_3592499.json,1
22,SOFTVERS,version 4.6,1,figshare_5532214.json,1
23,SOFTVERS,2016.1,1,zenodo_3228177.json,1
24,SOFTVERS,v. 5.0,1,zenodo_51185.json,1
25,SOFTVERS,4.6,1,zenodo_259443.json,1
26,SOFTVERS,v. 2016.4,1,zenodo_3950029.json,1
27,SOFTVERS,2020.6,1,zenodo_6349893.json,1
28,SOFTVERS,2018.0,1,zenodo_1488094.json,1
29,SOFTVERS,2018,1,zenodo_6755131.json,1
30,SOFTVERS,7,1,zenodo_1118682.json,1
31,SOFTVERS,5.1,1,zenodo_573274.json,1
32,SOFTVERS,2.11b2,1,zenodo_5497661.json,1
33,SOFTVERS,2.0,1,zenodo_3696970.json,1
34,SOFTVERS,2.6.3,1,figshare_22182562.json,1
35,SOFTVERS,2018.1,1,figshare_8003306.json,1
36,SOFTVERS,4.6.5,1,zenodo_3908769.json,1
37,SOFTVERS,v9.16,1,figshare_13135976.json,1
38,SOFTVERS,v.4.6.5,1,figshare_13135976.json,1

## Simulation time ⏱

In [49]:
list_entities(entities_df, "STIME")

,category,entity,occurrence,annotation_files,number_of_files
0,STIME,500ns,12,"zenodo_1009027.json,zenodo_1009607.json",2
1,STIME,200 ns,8,"figshare_4806544.json,zenodo_1118682.json,zeno...",6
2,STIME,500 ns,8,"zenodo_17550324.json,zenodo_259443.json,zenodo...",7
3,STIME,100 ns,6,"figshare_22182562.json,zenodo_247386.json,zeno...",6
4,STIME,1 microsecond,6,"figshare_20485017.json,figshare_20485059.json,...",6
...,...,...,...,...,...
57,STIME,hundred nanosecond,1,figshare_13135976.json,1
58,STIME,370 ns,1,zenodo_1198454.json,1
59,STIME,300 nanoseconds,1,zenodo_5153261.json,1
60,STIME,150 ns,1,zenodo_3988469.json,1
61,STIME,5000 ns,1,zenodo_6817824.json,1

## Temperature 🌡️

In [50]:
list_entities(entities_df, "TEMP")

,category,entity,occurrence,annotation_files,number_of_files
0,TEMP,310k,13,"figshare_8046437.json,zenodo_1009607.json,zeno...",7
1,TEMP,310 k,12,"figshare_11808396.json,figshare_13135976.json,...",10
2,TEMP,300 k,7,"figshare_2615170.json,figshare_4806544.json,ze...",6
3,TEMP,298 k,7,"figshare_20485017.json,figshare_20485059.json,...",6
4,TEMP,325k,5,"zenodo_1009027.json,zenodo_1009607.json",2
5,TEMP,303k,4,"zenodo_1009607.json,zenodo_13853.json,zenodo_2...",4
6,TEMP,313 k,3,"zenodo_1118682.json,zenodo_1293762.json",2
7,TEMP,320k,2,zenodo_1009027.json,1
8,TEMP,298.15,2,"zenodo_30904.json,zenodo_34415.json",2
9,TEMP,323 k,2,"zenodo_51750.json,zenodo_53212.json",2
10,TEMP,298k,2,zenodo_1167532.json,1
11,TEMP,338k,2,zenodo_1009027.json,1
12,TEMP,363 k,2,zenodo_7007107.json,1
13,TEMP,358k,2,zenodo_3950029.json,1
14,TEMP,288k,2,zenodo_3950029.json,1
15,TEMP,323k,2,"zenodo_14591.json,zenodo_15550.json",2
16,TEMP,310,1,zenodo_2653735.json,1
17,TEMP,298,1,zenodo_2653735.json,1
18,TEMP,285,1,zenodo_2653735.json,1
19,TEMP,322k,1,zenodo_1009027.json,1
20,TEMP,315k,1,zenodo_1009027.json,1
21,TEMP,338 k,1,zenodo_1009027.json,1
22,TEMP,315,1,zenodo_1009027.json,1
23,TEMP,37°c,1,zenodo_3988469.json,1
24,TEMP,310.15°k,1,zenodo_3988469.json,1
25,TEMP,295.15 k,1,zenodo_17550324.json,1
26,TEMP,295 k,1,figshare_4541035.json,1
27,TEMP,473.15 k,1,figshare_13836577.json,1
28,TEMP,340 k,1,zenodo_6380887.json,1
29,TEMP,225 k,1,zenodo_4106413.json,1
30,TEMP,200,1,zenodo_4106413.json,1
31,TEMP,130 k,1,figshare_22213635.json,1
32,TEMP,293 k,1,zenodo_259443.json,1
33,TEMP,90 ˚c,1,zenodo_7007107.json,1
34,TEMP,363k,1,zenodo_7007107.json,1
35,TEMP,303,1,zenodo_247386.json,1
36,TEMP,333 k,1,zenodo_2653735.json,1
37,TEMP,320,1,zenodo_2653735.json,1
38,TEMP,360 k,1,zenodo_6791876.json,1